data.keyset = _gauss_int32
data.size   = _1e5
data.seed   = 42

index.types = _binary; _exponential; _interpolation; \
              _pla_greedy; _pla_spline; _pla_convex; \
              _net_sigmoid; _net_relu; _net_leaky_relu; _net_softsign
index.err   = _8; _32; _64

net.layers           = 4,4
net.train.loss       = _squared
net.train.epochs     = 20
net.train.batch.size = 32
net.train.seed       = 42

out.path = out
